package Code.lexical;

public class enums {
    public enum TokenType {
        ID,
        INTEGER,
        FLOAT,
        EQ,
        EQEQ,
        LESSER,
        GREATER,
        NOTEQ,
        LESSEROREQUAL,
        GREATEROREQUAL,
        PLUS,
        MINUS,
        STAR,
        SLASH,
        OPENPAR,
        CLOSEDPAR,
        OPENCURLYBRACE,
        CLOSEDCURLYBRACE,
        OPENBRACKET,
        CLOSEDBRACKET,
        WHILE,
        LOCALVAR,
        OR,
        NOT,
        SEMICOLON,
        AND,
        THEN,
        IF,
        CONSTRUCTOR,
        VOID,
        CLASS,
        ELSE,
        FUNCTION,
        SELF,
        READ,
        PUBLIC,
        PRIVATE,
        RETURN,
        ISA,
        WRITE,
        DOT,
        ATTRIBUTE,
        COLON,
        DOUBLECOLON,
        COMMA,
        ONELINECOMMENT,
        MULTIPLELINECOMMENT,
        ARROW,
        EOF, //End of file
        INVALIDNUM,
        INVALIDCHAR,
        INVALIDID,
        UNKNOWN
    }

}
